#!/usr/bin/env ruby

R.eval('rbbt.loaded=T')
GENES =<<-EOF
ERBB3
SRCAP
IDH1
SRRM4
LRIG3
E2F7
CACNA1E
DNAH11
SERPINA6
NFAT5
MUC16
MUC17
PTCH1
RYR2
GREB1
LRRC37A3
MYBPC2
LYST
TTN
FGA
TP53
CHAF1B
OR2F1
COL2A1
ASCL3
DYNC1H1
CHD9
CCDC138
DOCK3
SENP6
CSMD1
APOB
COL1A2
GLDN
LILRA3
STX2
RAI1
RYR1
IDH2
COL5A3
LRRTM3
OR4C46
TRPC4
SH3GL3
SIPA1L3
LAMB3
USH2A
GPR98
HSPA12B
EIF2AK3
TRIM2
TNKS
ALMS1
DGKD
LRP1B
ZNF677
SETD2
PPP4R4
PCLO
PDGFRL
BLNK
MDH2
EOF
genes = GENES.split("\n")
organisms = %w(Hsa/jun2011 Hsa/may2009 Hsa/jan2013 Hsa)

require 'rbbt/workflow'

Workflow.require_workflow "Genomics"
require 'rbbt/entity/gene'

Workflow.require_workflow "Enrichment"


jobs = []
Enrichment::DATABASES.each do |database|
  organisms.each do |organism|
    jobs << Enrichment.job(:enrichment, "BOOTSTRAP", :list => genes.dup, :organism => organism, :database => database)
  end
end

jobs.each do |job|
  job.fork
  job.grace
end

Step.wait_for_jobs(jobs)
